# Generated by Django 3.2.6 on 2022-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comptes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
